# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171110_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='lessons_conducted',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='lessons_taken',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
