# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('media_caption', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson')),
            ],
        ),
    ]
