# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_lessoncreator'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonpart',
            name='approved_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by', to='profiles.LessonCreator'),
        ),
        migrations.AddField(
            model_name='lessonpart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonpart',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to='profiles.LessonCreator'),
        ),
        migrations.AddField(
            model_name='lessonpart',
            name='lesson_status',
            field=models.CharField(choices=[('ST', 'Started'), ('FI', 'Finished'), ('SC', 'Second Check'), ('AP', 'Approved')], default='ST', max_length=2),
        ),
        migrations.AddField(
            model_name='lessonpart',
            name='second_checked_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_checked_by', to='profiles.LessonCreator'),
        ),
        migrations.AddField(
            model_name='lessonpart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lessonpart',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to='profiles.LessonCreator'),
        ),
    ]
