# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_creator', '0003_auto_20171123_1811'),
        ('lessons', '0003_auto_20171118_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonpart',
            name='approved',
        ),
        migrations.AddField(
            model_name='lessonpart',
            name='lesson_status',
            field=models.CharField(choices=[('ST', 'Started'), ('FI', 'Finished'), ('SC', 'Second Check'), ('AP', 'Approved')], default='ST', max_length=2),
        ),
        migrations.AddField(
            model_name='lessonpart',
            name='second_checked_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='second_checked_by', to='lesson_creator.LessonCreator'),
        ),
        migrations.AlterField(
            model_name='lessonpart',
            name='approved_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='lesson_creator.LessonCreator'),
        ),
        migrations.AlterField(
            model_name='lessonpart',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='lesson_creator.LessonCreator'),
        ),
    ]
