# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_auto_20171117_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.TeacherProfile')),
            ],
        ),
    ]
