# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_creator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessoncreator',
            old_name='creator',
            new_name='profile',
        ),
    ]
