# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_creator', '0002_auto_20171118_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessoncreator',
            old_name='profile',
            new_name='teacher',
        ),
    ]
